### ISSUE TITLE
Question about cropping operation

### ISSUE THREAD

**Issue by daniel-bogdoll** [wayveai/mile#25]
Hey Anthony,

I have a question w.r.t to your cropping of the input image :) I tried to figure it out based on the paper and your PhD thesis, but I couldn't find anything besides Table C.7.

Given the 600 x 960 input image, you perform a crop operation, which leads to a 320 x 832 image:

```
_C.IMAGE.SIZE = (600, 960)
_C.IMAGE.CROP = [64, 138, 896, 458]  # (left, top, right, bottom)
```

I was wondering about your motivation for that - alternatives seem to be a different resolution in CARLA or a scaling operation? As I am personally interested in reconstructions in the same shape as the original input, a better understanding would help me going forward :)

Best
Daniel

**Comment by anthonyhu** [comment]
Hello, This crop was done to make to reduce the spatial feature size after convolving the image with an encoder (to save compute). I've cropped mainly the sky, and some of the side of the image. Also made sure the resulting dimensions were divisible 64 so that there's no issue with downsampling. I hope this helps!

**Comment by daniel-bogdoll** [comment]
Thanks! I'll try getting it to run properly without cropping, let's see how that will go :D
