### ISSUE TITLE
How did you get evaluation result for Expert in Table 1 in the paper?

### ISSUE THREAD

**Issue by airobotis** [wayveai/mile#39]
@anthonyhu 

1. How did you get evaluation result for Expert in Table 1 in the paper?

how was expert data collected and evaluated in the new environment?
I know that Roach agent was used to acquire data for learning, but I am curious about how expert data was acquired and evaluated in the new environment.

2.  "averaged across three runs."

could you explain more aoubt "averaged across three runs."
how many scenarios did you excute per run ?
Are the MILE results in Table.1 repeated three times with the New town, new weathers settings listed in Appendix D.3?

Thanks always.

**Comment by anthonyhu** [comment]
Hello, to answer your questions:

1. By running the data collection script, you should also get the metrics (driving score etc) related to the runs. 
2. We just ran the eval script `bash run/evaluate.sh` as indicated in the readme 3 times, in order to account for the stochastic nature of the carla environment.
